version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: rotules-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rotules_db
      MYSQL_USER: rotules_user
      MYSQL_PASSWORD: rotules_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: