server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rotules_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: rotules_user
    password: rotules_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          clover:
            client-id: ${spring.security.oauth2.client.registration.clover.client-id}
            client-secret: ${spring.security.oauth2.client.registration.clover.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/api/v1/clover/callback"
            scope: INVENTORY_READ,PAYMENTS_READ,PAYMENTS_WRITE
        provider:
          clover:
            authorization-uri: https://apisandbox.dev.clover.com/oauth/v2/authorize
            token-uri: https://apisandbox.dev.clover.com/oauth/v2/token
            user-info-uri: https://apisandbox.dev.clover.com/v3/merchants/current
            user-name-attribute: id

app:
  jwt:
    secret: tMjrfr5CfTFcfX6drB9X+vHc4+7ytGvrIB6vcnUNc72OT69j0ZTIJf1rAw6i1s/b
    expiration: 86400000 # 24 heures en millisecondes

logging:
  level:
    root: DEBUG